# -*- coding: utf-8 -*-
"""setup

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yDO4umzla4SGFDE-UMpMHSiZfJRzOsi4
"""

from setuptools import setup, find_packages
from pathlib import Path

# Read README for long description
this_directory = Path(__file__).parent
long_description = (this_directory / "README.md").read_text(encoding="utf-8")

setup(
    name="isro-mission-knowledge-graph",
    version="1.0.0",
    author="ISRO Mission Navigator Team",
    author_email="your-email@example.com",
    description="AI Knowledge Graph Builder for Enterprise Intelligence - ISRO Mission Navigator",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/your-username/isro-mission-knowledge-graph",

    packages=find_packages(
        include=[
            "module_1_data_ingestion*",
            "module_2_entity_extraction*",
            "module_3_graph_construction*",
            "module_4_rag_search*",
            "module_5_dashboard*",
            "utils*",
            "config*"
        ]
    ),

    install_requires=[
        # Core
        "pandas>=2.0.0",
        "numpy>=1.24.0",
        "scikit-learn>=1.3.0",
        "nltk>=3.8.0",

        # NLP & AI
        "spacy>=3.7.0",
        "transformers>=4.35.0",
        "sentence-transformers>=2.2.2",
        "torch>=2.0.0",

        # Knowledge Graph
        "neo4j>=5.0.0",
        "networkx>=3.0",
        "py2neo>=2021.2.4",

        # RAG & LLM
        "langchain>=0.1.0",
        "langchain-community>=0.0.20",
        "langchain-openai>=0.1.0",
        "openai>=1.0.0",
        "faiss-cpu>=1.7.4",
        "pinecone-client>=3.0.0",
        "tiktoken>=0.5.0",

        # Dashboard & Visualization
        "flask>=3.0.0",
        "flask-cors>=4.0.0",
        "plotly>=5.15.0",
        "dash>=2.14.0",
        "streamlit>=1.30.0",
        "matplotlib>=3.7.0",
        "seaborn>=0.12.0",

        # Utilities
        "python-dotenv>=1.0.0",
        "tqdm>=4.65.0",
        "pyyaml>=6.0",
        "requests>=2.30.0",
        "beautifulsoup4>=4.12.0",
        "jupyter>=1.0.0",
        "ipykernel>=6.25.0",
    ],

    extras_require={
        "dev": [
            "pytest>=7.4.0",
            "black>=24.0.0",
            "flake8>=6.0.0",
        ],
        "colab": [
            "google-colab",
        ],
        "gpu": [
            "torch",
            "faiss-gpu",
        ]
    },

    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "Intended Audience :: Developers",
        "Intended Audience :: Education",
        "Intended Audience :: Science/Research",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Database :: Database Engines/Servers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
    ],

    python_requires=">=3.8",

    keywords=[
        "knowledge-graph",
        "isro",
        "rag",
        "semantic-search",
        "neo4j",
        "langchain",
        "enterprise-ai",
        "mission-navigator",
        "ai-knowledge-graph"
    ],

    include_package_data=True,
    zip_safe=False,
)